Chieu6_Tuan3_2080600088/Controllers/TheLoaiController.cs
using Chieu6_Tuan3_2080600088;
using Chieu6_Tuan3_2080600088.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
namespace DemoLinq.Controllers
{
    public class TheloaiController : Controller
    {
        // GET: Theloai
       MyDataDataContext data = new MyDataDataContext();
        //-------------Index-Theloai------------
        public ActionResult Index()
        {
            var all_theloai = from tt in data.TheLoais select tt;
            return View(all_theloai);
        }
        //-------------Detail-------------------
        public ActionResult Detail(int id)
        {
            var D_theloai = data.TheLoais.Where(m => m.maloai == id).First();
            return View(D_theloai);
        }
        //-------------Create-------------------
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(FormCollection collection, TheLoai tl)
        {
            var ten = collection["tenloai"];
            if (string.IsNullOrEmpty(ten))
            {
                ViewData["Error"] = "Don't empty!";
            }
            else
            {
                tl.tenloai = ten;
                data.TheLoais.InsertOnSubmit(tl);
                data.SubmitChanges();
                return RedirectToAction("Index");
            }
            return this.Create();
        }
        //-------------Edit-------------------
        public ActionResult Edit(int id)
        {
            var E_category = data.TheLoais.First(m => m.maloai == id);
            return View(E_category);
        }
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            
        var theloai = data.TheLoais.First(m => m.maloai == id);
            var E_tenloai = collection["tenloai"];
            theloai.maloai = id;
            if (string.IsNullOrEmpty(E_tenloai))
            {
                ViewData["Error"] = "Don't empty!";
            }
            else
            {
                theloai.tenloai = E_tenloai;
                UpdateModel(theloai);
                data.SubmitChanges();
                return RedirectToAction("Index");
            }
            return this.Edit(id);
        }
        //-------------Delete-------------------
        public ActionResult Delete(int id)
        {
            var D_theloai = data.TheLoais.First(m => m.maloai == id);
            return View(D_theloai);
        }
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            var D_theloai = data.TheLoais.Where(m => m.maloai == id).First();
            data.TheLoais.DeleteOnSubmit(D_theloai);
            data.SubmitChanges();
            return RedirectToAction("Index");
        }
    }
}

Chieu6_Tuan3_2080600088/Views/TheLoai/Create.cshtml
{
 ViewBag.Title = "Create";
 Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Create</h2>
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    <fieldset>
        <p>
            Tên thể loại:
            @Html.TextBox("tenloai")<font color="red">@ViewData["Error"]</font>
        </p>
        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Chieu6_Tuan3_2080600088/Views/TheLoai/Delete.cshtml
@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Delete</h2>
<fieldset>
    <div class="display-label">Mã loại: @Html.Encode(Model.maloai)</div>
    <div class="display-lable">Tên loại: @Html.Encode(Model.tenloai)</div>
</fieldset>
@using (Html.BeginForm())
{
    <p>
        <input type="submit" value="Delete" />
        @Html.ActionLink("Back to List", "Index")
    </p>
}

Chieu6_Tuan3_2080600088/Views/TheLoai/Detail.cshtml
@{
    ViewBag.Title = "Detail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Detail</h2>
<fieldset>
    <div class="display-label">Mã loại: @Model.maloai</div>
    <div class="display-label">Tên loại: @Model.tenloai</div>
</fieldset>
@using (Html.BeginForm())
{
    <p>
        @Html.ActionLink("Delete", "Delete", new { id = Model.maloai }) |
        @Html.ActionLink("Edit", "Edit", new { id = Model.maloai }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

Chieu6_Tuan3_2080600088/Views/TheLoai/Edit.cshtml
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Edit</h2>
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    <fieldset>
        <div class="editor-field">
            Tên loại:
            @Html.TextBox("tenloai");
            @ViewData["Error"]
        </div>
        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}
<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Chieu6_Tuan3_2080600088/Views/TheLoai/Index.cshtml
@model IEnumerable< Chieu6_Tuan3_2080600088.Models.TheLoai>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Index</h2>
<table border="1px">
    <tr>
        <th>Mã thể loại</th>
        <th>Tên thể loại </th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.maloai</td>
            <td>@item.tenloai</td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.maloai }) |
                @Html.ActionLink("Detail", "Detail", new { id = item.maloai }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.maloai })
            </td>
        </tr>
    }
</table>
@Html.ActionLink("Create", "Create", "Theloai")